# print(dir("Hello world!"))
# print('--------------------------------')
# help("Hello world!")
# print('--------------------------------')
# help(str)
# print('--------------------------------')
help()
